# ui_styles.py

# --- Colors ---
# -- Base colors --
COLOR_BLACK = "#000000"
COLOR_WHITE = "#FFFFFF"

# -- Page colors --
PAGE_BACKGROUND_COLOR = "#FFFFFF"
PANEL_BACKGROUND_COLOR = "#F5F5F5"

# -- Table colors --
TABLE_HEADER_BACKGROUND_COLOR = "#363636"
TABLE_ROW_PRIMARY_BACKGROUND_COLOR = "#EEEEEE"
TABLE_ROW_SECONDARY_BACKGROUND_COLOR = "#E0E0E0"

# -- Control colors --
# - Primary buttons -
CONTROL_PRIMARY_BACKGROUND_COLOR = "#D9D9D9"
CONTROL_PRIMARY_BACKGROUND_ACTIVE_COLOR = "#C0C0C0"

# - Secondary buttons -
CONTROL_SECONDARY_BACKGROUND_COLOR = "#363636"
CONTROL_SECONDARY_BACKGROUND_ACTIVE_COLOR = "#F0F0F0"

# -- Text colors ---
TEXT_PRIMARY_COLOR = "#000000"
TEXT_SECONDARY_COLOR = "#FFFFFF"

# -- Accent colors --
ACCENT_PRIMARY_COLOR = "#F1C40F"

# --- Fonts ---
TITLE_FONT = ("Segoe UI", 14, "bold")
SUBTITLE_FONT = ("Segoe UI", 10, "normal")
TABLE_HEADER_FONT = ("Segoe UI", 10, "bold")
TEXT_FONT = ("Segoe UI", 10, "normal")
NUMBER_FONT = ("Segoe UI", 10, "bold")
BUTTON_FONT = ("Segoe UI", 10, "normal")

# --- Layout ---
# -- Padding --
# - Title padding -
TITLE_PADX = 20
TITLE_PADY_TOP = 15
TITLE_PADY_BOTTOM = 5

# - Subtitle padding -
SUBTITLE_PADX = 20
SUBTITLE_PADY_TOP = 0
SUBTITLE_PADY_BOTTOM = 15

# - Section padding -
TABLE_HEADER_PADX = 10
TABLE_HEADER_PADY = 6

# - Statement padding -
STATEMENT_PADX = 10
STATEMENT_PADY = 8

# - Row padding -
ROW_PADY = 1
ROW_INNER_PADX = 10
ROW_INNER_PADY = 8

# -- Question row --
NUMBER_WIDTH = 4
STATEMENT_WRAP = 650
LIKERT_BUTTON_WIDTH = 3
LIKERT_BUTTON_PADX = 4

# -- Separator between rows
SEPARATOR_HEIGHT = 1
SEPARATOR_COLOR = COLOR_WHITE